package com.blogrestapi.DTO;


import java.util.Date;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class PostDTO {
    
    private int postId; // No validation if auto-generated by MongoDB

    @NotBlank(message = "Post title is mandatory")
    @Size(min = 5, max = 100, message = "Post title must be between 5 and 100 characters")
    private String postTitle;
    
    @NotBlank(message = "Content is mandatory")
    @Size(min = 10, message = "Content must be at least 10 characters long")
    private String content;
    // @NotBlank(message = "Image URL is mandatory")
    private String image;

    // @NotNull(message = "Post date cannot be null")
    // @PastOrPresent(message = "Post date must be in the past or present")
    private Date postDate;
    private int userId;
    private int categoryId;
}
